# Generated by Django 5.1.3 on 2024-11-21 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('pizza_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('category', models.TextField()),
                ('size', models.TextField()),
                ('image', models.ImageField(upload_to='media/pizza/')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='points',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
