# Generated by Django 5.1.3 on 2024-11-21 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pizza_remove_customuser_points_delete_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_id',
            field=models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
