# Generated by Django 5.1.3 on 2024-11-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pizza_pizza_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('client_id', models.IntegerField()),
                ('pizza_id', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_id',
            field=models.TextField(editable=False, primary_key=True, serialize=False),
        ),
    ]
